name: "Build and Push Image"

on:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    name: "Docker Build Push"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: ${{ secrets.DOCKER_REPO }} 
         tag_with_ref: true
         tag_with_sha: true
         tags: latest
